---
version: "2"

plugins:
  brakeman:
    enabled: true
  editorconfig:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  scss-lint:
    enabled: true

exclude_patterns:
  - Gemfile.lock
  - "**/*.png"
  - db/
  - "*.js"
