language: ruby

rvm:
  - 2.6.0

global:
  - CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID
  - RAILS_ENV=test

addons:
  postgresql: 9.6

notifications:
  email:
    recipients:
      - ramonsantos.pe@gmail.com
    on_success: change
    on_failure: always

before_install:
  - gem update --system
  - gem install bundler

cache: bundler

branches:
  only:
    - master

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec
