version: "3.3"

services:
  postgres-compose:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - /home/ramonsantos/docker/PostgreSQL:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin-compose:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "ramonsantos.pe@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports:
      - "15432:15432"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
